In [1]:
import numpy as np
from sklearn.model_selection import train_test_split

# Sample data
my_data = np.array([[1, 2, 0], [3, 4, 1], [5, 6, 1], [7, 8, 0], [9, 10, 1], [11, 12, 0]])

# Split the data using train_test_split
my_X = my_data[:, :-1]
my_y = my_data[:, -1]
my_X_train, my_X_test, my_y_train, my_y_test = train_test_split(my_X, my_y, test_size=0.2, random_state=42)

# Print the results
print('my_X_train:')
print(my_X_train)
print('\nmy_y_train:')
print(my_y_train)
print('\nmy_X_test:')
print(my_X_test)
print('\nmy_y_test:')
print(my_y_test)


my_X_train:
[[11 12]
 [ 5  6]
 [ 9 10]
 [ 7  8]]

my_y_train:
[0 1 1 0]

my_X_test:
[[1 2]
 [3 4]]

my_y_test:
[0 1]


In [2]:
import numpy as np

# Sample data
my_data = np.array([[1, 2, 0], [3, 4, 1], [5, 6, 1], [7, 8, 0]])

# Shuffle the data randomly
np.random.shuffle(my_data)

# Define the split fraction
my_split_fraction = 0.8
my_split = int(my_split_fraction * len(my_data))

# Split the data into training and testing sets
my_X_train = my_data[:my_split, :-1]
my_y_train = my_data[:my_split, -1]
my_X_test = my_data[my_split:, :-1]
my_y_test = my_data[my_split:, -1]

print('my_X_train:')
print(my_X_train)
print('\nmy_y_train:')
print(my_y_train)
print('\nmy_X_test:')
print(my_X_test)
print('\nmy_y_test:')
print(my_y_test)


my_X_train:
[[7 8]
 [1 2]
 [5 6]]

my_y_train:
[0 0 1]

my_X_test:
[[3 4]]

my_y_test:
[1]


In [3]:
import numpy as np

def custom_random_split(input_X, input_y, train_fraction):
    num_samples = input_X.shape[0]

    # Shuffle the indices randomly
    shuffled_indices = np.random.permutation(num_samples)

    # Calculate the split index
    split_index = int(train_fraction * num_samples)

    # Select the first 'split_index' shuffled indices for training
    train_indices = shuffled_indices[:split_index]

    # Use the selected indices to split the data
    X_train = input_X[train_indices]
    y_train = input_y[train_indices]

    # The rest of the indices are for testing
    test_indices = shuffled_indices[split_index:]

    X_test = input_X[test_indices]
    y_test = input_y[test_indices]

    return (X_train, y_train, X_test, y_test)

# Sample data
my_data = np.array([[1, 2, 0], [3, 4, 1], [5, 6, 1], [7, 8, 0]])

# Split the data using custom_random_split
my_X_train, my_y_train, my_X_test, my_y_test = custom_random_split(my_data[:, :-1], my_data[:, -1], train_fraction=0.8)

# Print the results
print('my_X_train:')
print(my_X_train)
print('\nmy_y_train:')
print(my_y_train)
print('\nmy_X_test:')
print(my_X_test)
print('\nmy_y_test:')
print(my_y_test)


my_X_train:
[[3 4]
 [5 6]
 [1 2]]

my_y_train:
[1 1 0]

my_X_test:
[[7 8]]

my_y_test:
[0]


In [4]:
import numpy as np

# Sample data
my_data = np.array([[1, 2, 0], [3, 4, 1], [5, 6, 1], [7, 8, 0]])

# Define the split fraction
my_split_fraction = 0.8

# Calculate the split index
my_split = int(my_split_fraction * len(my_data))

# Split the data into training and testing sets
my_X_train = my_data[:my_split, :-1]
my_y_train = my_data[:my_split, -1]
my_X_test = my_data[my_split:, :-1]
my_y_test = my_data[my_split:, -1]

# Print the results
print('my_X_train:')
print(my_X_train)
print('\nmy_y_train:')
print(my_y_train)
print('\nmy_X_test:')
print(my_X_test)
print('\nmy_y_test:')
print(my_y_test)


my_X_train:
[[1 2]
 [3 4]
 [5 6]]

my_y_train:
[0 1 1]

my_X_test:
[[7 8]]

my_y_test:
[0]


In [5]:
import numpy as np
from sklearn.model_selection import train_test_split

# Sample data
my_data = np.array([[1, 2, 0], [3, 4, 1], [5, 6, 1], [7, 8, 0]])

# Split the data using train_test_split
my_X = my_data[:, :-1]
my_y = my_data[:, -1]
my_X_train, my_X_test, my_y_train, my_y_test = train_test_split(my_X, my_y, test_size=0.2, random_state=42)

# Print the results
print('my_X_train:')
print(my_X_train)
print('\nmy_y_train:')
print(my_y_train)
print('\nmy_X_test:')
print(my_X_test)
print('\nmy_y_test:')
print(my_y_test)


my_X_train:
[[7 8]
 [1 2]
 [5 6]]

my_y_train:
[0 0 1]

my_X_test:
[[3 4]]

my_y_test:
[1]


In [6]:
import numpy as np

class MyKNN:
    def __init__(self, n_neighbors=5):
        self.n_neighbors = n_neighbors
        self.my_X_train = None
        self.my_y_train = None

    def fit(self, my_X, my_y):
        self.my_X_train = my_X
        self.my_y_train = my_y

    def predict(self, my_X):
        my_y_pred = np.zeros(my_X.shape[0])

        for i, my_x in enumerate(my_X):
            # Calculate distances between the current sample and all training samples
            my_distances = np.linalg.norm(self.my_X_train - my_x, axis=1)

            # Get indices of the k-nearest neighbors
            my_k_indices = np.argsort(my_distances)[:self.n_neighbors]

            # Find the most common class label among the neighbors
            my_neighbor_labels = self.my_y_train[my_k_indices]
            my_unique_labels, my_label_counts = np.unique(my_neighbor_labels, return_counts=True)
            my_y_pred[i] = my_unique_labels[np.argmax(my_label_counts)]

        return my_y_pred


In [7]:
import numpy as np

# Create an instance of the MyKNN class with default settings (5 neighbors)
my_knn = MyKNN()

# Define your training data and labels (example data)
my_X_train = np.array([[1, 2], [2, 3], [3, 4], [4, 5]])
my_y_train = np.array([0, 1, 0, 1])

# Fit the MyKNN model with the training data and labels
my_knn.fit(my_X_train, my_y_train)


In [8]:
import numpy as np
from sklearn.metrics import accuracy_score

# Define the MyKNN class
class MyKNN:
    def __init__(self, n_neighbors=5):
        self.n_neighbors = n_neighbors
        self.my_X_train = None
        self.my_y_train = None

    def fit(self, my_X, my_y):
        self.my_X_train = my_X
        self.my_y_train = my_y

    def predict(self, my_X):
        my_y_pred = np.zeros(my_X.shape[0])

        for i, my_x in enumerate(my_X):
            # Calculate distances between the current sample and all training samples
            my_distances = np.linalg.norm(self.my_X_train - my_x, axis=1)

            # Get indices of the k-nearest neighbors
            my_k_indices = np.argsort(my_distances)[:self.n_neighbors]

            # Find the most common class label among the neighbors
            my_neighbor_labels = self.my_y_train[my_k_indices]
            my_unique_labels, my_label_counts = np.unique(my_neighbor_labels, return_counts=True)
            my_y_pred[i] = my_unique_labels[np.argmax(my_label_counts)]

        return my_y_pred

    def evaluate(self, my_X_test, my_y_test):
        # Predict labels for the test data
        my_y_pred = self.predict(my_X_test)

        # Calculate accuracy
        my_accuracy = accuracy_score(my_y_test, my_y_pred)

        return my_accuracy, my_y_pred

# Create an instance of the MyKNN class with default settings (5 neighbors)
my_knn = MyKNN()

# Define your training data and labels (example data)
my_X_train = np.array([[1, 2], [2, 3], [3, 4], [4, 5]])
my_y_train = np.array([0, 1, 0, 1])

# Fit the MyKNN model with the training data and labels
my_knn.fit(my_X_train, my_y_train)

# Define your test data and labels (example data)
my_X_test = np.array([[1.5, 2.5], [3.5, 4.5]])
my_y_test = np.array([0, 0])

# Evaluate the model and get predictions and accuracy
my_accuracy, my_y_pred = my_knn.evaluate(my_X_test, my_y_test)

# Print the results
print("Predictions:", my_y_pred)
print("Accuracy:", my_accuracy)


Predictions: [0. 0.]
Accuracy: 1.0


In [9]:
from sklearn.metrics import accuracy_score
import numpy as np

# Sample data (replace with your data)
my_X_train = np.array([[1, 2], [2, 3], [3, 4], [4, 5]])
my_y_train = np.array([0, 1, 0, 1])
my_X_test = np.array([[2, 2], [3, 3]])
my_y_true = np.array([0, 1])

# Define a range of hyperparameters to search
my_n_neighbors_values = [3, 5, 7]
my_weights_values = ['uniform', 'distance']

best_accuracy = 0
best_params = {}

# Iterate through all hyperparameter combinations
for my_n_neighbors in my_n_neighbors_values:
    for my_weights in my_weights_values:
        # Create and train a KNN model with the current hyperparameters
        class MyKNN:
            def __init__(self):
                self.my_n_neighbors = my_n_neighbors
                self.my_weights = my_weights
                self.my_X_train = None
                self.my_y_train = None

            def fit(self, my_X, my_y):
                self.my_X_train = my_X
                self.my_y_train = my_y

            def predict(self, my_X):
                my_y_pred = []

                for my_x in my_X:
                    # Calculate distances between the current sample and all training samples
                    my_distances = [np.linalg.norm(my_x - my_x_train) for my_x_train in self.my_X_train]

                    # Get indices of the k-nearest neighbors
                    my_k_indices = np.argsort(my_distances)[:self.my_n_neighbors]

                    # Find the most common class label among the neighbors
                    my_neighbor_labels = [self.my_y_train[i] for i in my_k_indices]
                    my_unique_labels, my_label_counts = np.unique(my_neighbor_labels, return_counts=True)
                    my_y_pred.append(my_unique_labels[np.argmax(my_label_counts)])

                return np.array(my_y_pred)

        my_knn = MyKNN()
        my_knn.fit(my_X_train, my_y_train)

        # Make predictions on the test set
        my_y_pred = my_knn.predict(my_X_test)

        # Calculate accuracy
        my_accuracy = accuracy_score(my_y_true, my_y_pred)

        # Check if this combination of hyperparameters gives a better accuracy
        if my_accuracy > best_accuracy:
            best_accuracy = my_accuracy
            best_params = {'n_neighbors': my_n_neighbors, 'weights': my_weights}

print(f"Best Hyperparameters: {best_params}")
print(f"Best Accuracy: {best_accuracy}")


Best Hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Best Accuracy: 0.5
